import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Navbar from "./components/Nav";
import SearchBar from "./components/search";
import { Button } from "@/components/ui/button";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="ml-12"> {/* margin left equivalent to Navbar width */}
          <div className="">
            <Navbar />
          </div>
          <div className="absolute inset-x-0 top-0 ml-12 flex justify-center">
            <SearchBar name='barra de búsqueda'>
              <Button variant="outline" type="submit">Subscribe</Button>
              <Button variant="outline" type="submit">Subscribe</Button>
            </SearchBar>
          </div>
          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
